/* ==========================================================================
   CAKE LOVER — CENTRALIZED REAL-TIME DATASET
   Loaded by all browsers (Chrome, Edge, Safari, Mobile) and synced live.
   ========================================================================== */

window.CAKELOVER_DATA = {
  categories: [
    { id: 'caramel-nut', name: 'Caramel Nut' },
    { id: 'flavored', name: 'Flavored' },
    { id: 'extreme-combo', name: 'Extreme Combo' },
    { id: 'choco-cakes', name: 'Choco Cakes' },
    { id: 'special-edition', name: 'Special Edition' },
    { id: 'premium-special', name: 'Premium Special' },
    { id: 'delight-cakes', name: 'Delight Cakes' },
    { id: 'customized-cakes', name: 'Customized Cakes' }
  ],

  products: [
    // === Caramel Nut Cakes ===
    { id:1,  name:"Choco Scotch Cake",          category:"caramel-nut",     tag:"1 kg + ½ kg FREE", basePrice:734,  originalPrice:1099, offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes/cakes/caramel chocolate.jfif", desc:"Delicious blend of rich chocolate and golden butterscotch crunch.", active:true },
    { id:2,  name:"Red Scotch Cake",            category:"caramel-nut",     tag:"1 kg + ½ kg FREE", basePrice:882,  originalPrice:1299, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes/cakes/Red velvet Cake .jfif", desc:"Soft red velvet sponge with a crispy butterscotch crunch layer.", active:true },
    { id:3,  name:"Ferro Scotch Cake",          category:"caramel-nut",     tag:"1 kg + ½ kg FREE", basePrice:750,  originalPrice:1150, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes/cakes/Southern Caramel Cake_ 5-Star Recipe You Must Try - My Favorite Recipes.jfif", desc:"Premium Ferrero-style hazelnut crunch combined with rich caramel.", active:true },
    { id:4,  name:"Rasmalai Scotch Cake",       category:"caramel-nut",     tag:"1 kg + ½ kg FREE", basePrice:706,  originalPrice:1050, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes/cakes/Crissie's Homemade _ Colorado Springs CO.jfif", desc:"Desi rasmalai milk sponge paired with golden butterscotch bits.", active:true },
    { id:5,  name:"Triple Scotch Cake",         category:"caramel-nut",     tag:"1 kg + ½ kg FREE", basePrice:750,  originalPrice:1150, offerText:"Buy 1kg get ½kg free", rating:4.75, img:"./cakes2/cakes2/butterscotch.jfif", desc:"Triple-layered caramel mousse and crispy praline nuggets.", active:true },
    { id:6,  name:"Milky Scotch Cake",          category:"caramel-nut",     tag:"1 kg + ½ kg FREE", basePrice:853,  originalPrice:1250, offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes2/cakes2/cake.jfif", desc:"Silky milk cream sponge infused with butterscotch crunch.", active:true },
    { id:7,  name:"Butterscotch Cake",          category:"caramel-nut",     tag:"1 kg + ½ kg FREE", basePrice:662,  originalPrice:990,  offerText:"Buy 1kg get ½kg free", rating:4.7, img:"./cakes2/cakes2/butterscotch.jfif", desc:"Classic golden butterscotch with real caramel drizzle.", active:true },

    // === Flavored Cakes ===
    { id:8,  name:"Classic Vanilla Cake",       category:"flavored",        tag:"1 kg + ½ kg FREE", basePrice:440,  originalPrice:650,  offerText:"Buy 1kg get ½kg free", rating:4.6, img:"./cakes2/cakes2/cake.jfif", desc:"Pure Madagascar vanilla bean cream over fluffy white sponge.", active:true },
    { id:9,  name:"White Forest Cake",          category:"flavored",        tag:"1 kg + ½ kg FREE", basePrice:603,  originalPrice:890,  offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes/cakes/White Forest Cake.jfif", desc:"White chocolate curls over vanilla sponge with cherry fillings.", active:true },
    { id:10, name:"Mango Cake",                 category:"flavored",        tag:"1 kg + ½ kg FREE", basePrice:574,  originalPrice:850,  offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes/cakes/Mango Chiffon Cake.jfif", desc:"Fresh Alphonso mango pulp blended into light whipped cream.", active:true },
    { id:11, name:"Pineapple Cake",             category:"flavored",        tag:"1 kg + ½ kg FREE", basePrice:574,  originalPrice:850,  offerText:"Buy 1kg get ½kg free", rating:4.7, img:"./cakes/cakes/Dole Whip Cake.jfif", desc:"Juicy pineapple compote layered with light vanilla cream.", active:true },
    { id:12, name:"Blueberry Cake",             category:"flavored",        tag:"1 kg + ½ kg FREE", basePrice:625,  originalPrice:920,  offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes2/cakes2/Blueberry Cake.jfif", desc:"Wild blueberry reduction swirled into smooth vanilla frosting.", active:true },
    { id:13, name:"Strawberry Cake",            category:"flavored",        tag:"1 kg + ½ kg FREE", basePrice:574,  originalPrice:850,  offerText:"Buy 1kg get ½kg free", rating:4.75, img:"./cakes/cakes/cakestrawberry.jfif", desc:"Fresh strawberry compote layered with sweet vanilla cream.", active:true },
    { id:14, name:"Red Velvet Cake",            category:"flavored",        tag:"1 kg + ½ kg FREE", basePrice:750,  originalPrice:1100, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes2/cakes2/Red Velvet White Chocolate.jfif", desc:"Soft crimson cocoa sponge layered with rich cream cheese.", active:true },
    { id:15, name:"Black Forest Cake [500 G]",  category:"flavored",        tag:"500g Pack",        basePrice:515,  originalPrice:750,  offerText:"500g Pack",            rating:4.8, img:"./cakes/cakes/Black forest cake recipe.jfif", desc:"Classic dark chocolate shavings with maraschino cherries in a half kg pack.", active:true },

    // === Extreme Combo Cakes ===
    { id:16, name:"Choco Vanilla Cake",         category:"extreme-combo",   tag:"1 kg + ½ kg FREE", basePrice:625,  originalPrice:920,  offerText:"Buy 1kg get ½kg free", rating:4.75, img:"./cakes2/cakes2/choconillla", desc:"Dual-flavored marble swirl of rich cocoa and pure vanilla.", active:true },
    { id:17, name:"Choco Strawberry Cake",      category:"extreme-combo",   tag:"1 kg + ½ kg FREE", basePrice:625,  originalPrice:920,  offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes/cakes/cakestrawberry.jfif", desc:"Decadent dark chocolate ganache paired with fresh strawberry cream.", active:true },
    { id:18, name:"Butterscotch And Blueberry Cake", category:"extreme-combo", tag:"1 kg + ½ kg FREE", basePrice:706, originalPrice:1050, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes2/cakes2/Blueberry Cake.jfif", desc:"Fruity blueberry swirls combined with crunchy butterscotch bits.", active:true },
    { id:19, name:"German Black Forest Cake",   category:"extreme-combo",   tag:"1 kg + ½ kg FREE", basePrice:721,  originalPrice:1080, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes/cakes/black-forest-gateau.jfif", desc:"Authentic German-style dark chocolate cake loaded with cherries.", active:true },
    { id:20, name:"German Chocolate Cake",      category:"extreme-combo",   tag:"1 kg + ½ kg FREE", basePrice:721,  originalPrice:1080, offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes/cakes/Dark Chocolate .jfif", desc:"Rich chocolate cake with coconut-pecan filling and fudge.", active:true },

    // === Choco Cakes ===
    { id:21, name:"Chocolate Cake",             category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:625,  originalPrice:920,  offerText:"Buy 1kg get ½kg free", rating:4.7, img:"./cakes2/cakes2/download (5).jfif", desc:"Rich moist cocoa sponge smothered in silky chocolate frosting.", active:true },
    { id:22, name:"Choco Truffle Cake",         category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:706,  originalPrice:1050, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes/cakes/download (3).jfif", desc:"Pure chocolate fudge layered with silky cream and truffle glaze.", active:true },
    { id:23, name:"Dead By Chocolate Cake",     category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:735,  originalPrice:1100, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes/cakes/Dark Chocolate .jfif", desc:"Triple-layer dark chocolate ganache for true cocoa lovers.", active:true },
    { id:24, name:"Choco Forest Cake",          category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:735,  originalPrice:1100, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes/cakes/black-forest-gateau.jfif", desc:"Extra chocolatey black forest loaded with dark cocoa curls.", active:true },
    { id:25, name:"Choco Excess Cake",          category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:735,  originalPrice:1100, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes2/cakes2/download (8).jfif", desc:"Overloaded with melted dark chocolate, fudge & choco chips.", active:true },
    { id:26, name:"Choco KitKat Cake",          category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:809,  originalPrice:1199, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes/cakes/download (5).jfif", desc:"Bordered with crispy KitKat bars and topped with choco balls.", active:true },
    { id:27, name:"Choco Walnut Cake",          category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:750,  originalPrice:1150, offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes/cakes/coffee_mocha_cake.jfif", desc:"Rich chocolate sponge packed with roasted crunchy walnuts.", active:true },
    { id:28, name:"Choco Oreo Cake",            category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:809,  originalPrice:1199, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes/cakes/download (3).jfif", desc:"Crushed Oreo cookie cream layered inside rich chocolate sponge.", active:true },
    { id:29, name:"Milky Truffle Cake",         category:"choco-cakes",     tag:"1 kg + ½ kg FREE", basePrice:809,  originalPrice:1199, offerText:"Buy 1kg get ½kg free", rating:4.75, img:"./cakes2/cakes2/cake3.jfif", desc:"Creamy milk chocolate truffle with white cocoa drippings.", active:true },

    // === Special Edition Cake ===
    { id:30, name:"Ritch Choco KitKat Cake",    category:"special-edition", tag:"1 kg + 1 kg FREE", basePrice:1469, originalPrice:2199, offerText:"Buy 1kg get 1kg free", rating:4.95, img:"./cakes/cakes/download (5).jfif", desc:"Luxury celebration cake wrapped in KitKat bars with rich truffle core.", active:true },

    // === Premium Special Cakes ===
    { id:31, name:"Black Forest Premium Cake",  category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes/cakes/Black forest cake recipe.jfif", desc:"Premium black forest layered with imported cherries & dark cacao.", active:true },
    { id:32, name:"Mango Premium Cake",         category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes/cakes/Mango Chiffon Cake.jfif", desc:"Alphonso mango cream cake with premium fruit glaze.", active:true },
    { id:33, name:"White Forest Premium Cake",  category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes/cakes/White Forest Cake.jfif", desc:"Belgian white chocolate curls with luxury cherry reduction.", active:true },
    { id:34, name:"Pineapple Premium Cake",     category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes/cakes/Dole Whip Cake.jfif", desc:"Fresh tropical pineapple compote over rich vanilla sponge.", active:true },
    { id:35, name:"Blueberry Premium Cake",     category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes2/cakes2/Blueberry Cake.jfif", desc:"Handpicked wild blueberry compote layered with whipped cream.", active:true },
    { id:36, name:"Blackcurrant Premium Cake",  category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes2/cakes2/download (4).jfif", desc:"Exotic blackcurrant berry glaze over soft vanilla sponge.", active:true },
    { id:37, name:"Red Velvet Premium Cake",    category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:955,  originalPrice:1390, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes2/cakes2/Red Velvet White Chocolate.jfif", desc:"Signature crimson cocoa cake with imported cream cheese icing.", active:true },
    { id:38, name:"Choco Truffle Premium Cake", category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes2/cakes2/download (8).jfif", desc:"Dense Belgian chocolate truffle cake finished with cocoa dust.", active:true },
    { id:39, name:"Butterscotch Premium Cake",  category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes2/cakes2/butterscotch.jfif", desc:"Golden caramel praline crunch with rich butterscotch mousse.", active:true },
    { id:40, name:"Ferro Premium Cake",         category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes/cakes/caramel chocolate.jfif", desc:"Ferrero hazelnut rocher mousse layered with dark chocolate fudge.", active:true },
    { id:41, name:"Lemon Premium Cake",         category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.75, img:"./cakes2/cakes2/Dream cake.jfif", desc:"Zesty lemon curd cream layered into fresh vanilla chiffon sponge.", active:true },
    { id:42, name:"Choco Almond Premium Cake",  category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes/cakes/download (5).jfif", desc:"Roasted California almonds embedded in rich chocolate ganache.", active:true },
    { id:43, name:"Milky Premium Cake",         category:"premium-special", tag:"1 kg + ½ kg FREE", basePrice:868,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes2/cakes2/download (6).jfif", desc:"Luscious condensed milk sponge with whipped white cream.", active:true },

    // === Delight Cakes ===
    { id:44, name:"Pista Delight Cake",         category:"delight-cakes",   tag:"1 kg + ½ kg FREE", basePrice:956,  originalPrice:1390, offerText:"Buy 1kg get ½kg free", rating:4.95, img:"./cakes2/cakes2/rasmalai cake.jfif", desc:"Real Iranian pistachio cream swirled into aromatic cardamom sponge.", active:true },
    { id:45, name:"Tender Coconut Delight Cake",category:"delight-cakes",   tag:"1 kg + ½ kg FREE", basePrice:881,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes/cakes/birthday cake.jfif", desc:"Fresh tender coconut malai folded into light vanilla cream.", active:true },
    { id:46, name:"Strawberry Delight Cake",    category:"delight-cakes",   tag:"1 kg + ½ kg FREE", basePrice:881,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.8, img:"./cakes/cakes/Sprinkle Birthday Cake _ Hungry Happenings.jfif", desc:"Luscious fresh strawberry crush layered with velvety cream.", active:true },
    { id:47, name:"Butterscotch Delight Cake",  category:"delight-cakes",   tag:"1 kg + ½ kg FREE", basePrice:881,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes/cakes/white-wedding-cake.jfif", desc:"Rich butterscotch cream with extra crispy golden praline.", active:true },
    { id:48, name:"Mango Delight Cake",         category:"delight-cakes",   tag:"1 kg + ½ kg FREE", basePrice:881,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.75, img:"./cakes/cakes/download (4).jfif", desc:"Sweet mango puree swirled into soft vanilla sponge.", active:true },
    { id:49, name:"Royal Choco Delight Cake",   category:"delight-cakes",   tag:"1 kg + ½ kg FREE", basePrice:881,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.9, img:"./cakes2/cakes2/download (7).jfif", desc:"Royal dark chocolate fudge with silky whipped cream accent.", active:true },
    { id:50, name:"Blueberry Delight Cake",     category:"delight-cakes",   tag:"1 kg + ½ kg FREE", basePrice:881,  originalPrice:1290, offerText:"Buy 1kg get ½kg free", rating:4.85, img:"./cakes2/cakes2/(13) Facebook.jfif", desc:"Wild blueberry crush layered with vanilla sponge & cream.", active:true },

    // === Customized Cakes (63 Bespoke AI Designed Cakes) ===
    { id:51,  name:"Bespoke Royal Butterfly Cake",       category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/Aug 7, 2026, 11_49_54 AM.png", desc:"Handcrafted royal butterfly themed celebration cake with edible sugar wings.", active:true },
    { id:52,  name:"Enchanted Fairy Tale Crown Cake",    category:"customized-cakes", tag:"Custom Design", basePrice:1599, originalPrice:2199, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 09_42_47 AM.png", desc:"Majestic princess crown cake layered with strawberry cream and golden fondant accents.", active:true },
    { id:53,  name:"Golden Luxury Pearl Birthday Cake",  category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 09_52_40 AM.png", desc:"Elegant white and gold pearl embellished tiered cake with handcrafted sugar flowers.", active:true },
    { id:54,  name:"Modern Pastel Floral Sculpted Cake", category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.85, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 09_54_46 AM.png", desc:"Minimalist pastel buttercream cake topped with fresh organic edible blooms.", active:true },
    { id:55,  name:"Whimsical Rainbow Unicorn Cake",     category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 09_57_20 AM.png", desc:"Magical unicorn cake with golden horn and pastel rainbow swirl mane.", active:true },
    { id:56,  name:"3D Teddy Bear Cloud Cake",          category:"customized-cakes", tag:"Custom Design", basePrice:1450, originalPrice:1950, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 09_58_34 AM.png", desc:"Adorable handcrafted 3D teddy bear sleeping on fluffy sugar clouds.", active:true },
    { id:57,  name:"Elegant Crimson Rose Tiered Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1699, originalPrice:2299, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_01_04 AM.png", desc:"Luxury 2-tier crimson red velvet cake with gold leaf and handcrafted sugar roses.", active:true },
    { id:58,  name:"Celestial Galaxy Shimmer Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.88, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_04_39 AM.png", desc:"Deep space navy galaxy mirror glaze cake with edible constellation sparkles.", active:true },
    { id:59,  name:"Vintage Victorian Bow & Pearl Cake", category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_09_12 AM.png", desc:"Coquette aesthetic vintage piped buttercream cake with satin sugar ribbons.", active:true },
    { id:60,  name:"Royal Gold & Velvet Jubilee Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1599, originalPrice:2199, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_10_54 AM.png", desc:"Grand milestone anniversary cake with 24k gold foil and dark chocolate fudge.", active:true },
    { id:61,  name:"Cute Woodland Baby Bear Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_16_22 AM.png", desc:"Charming forest theme baby shower cake with hand-painted woodland critters.", active:true },
    { id:62,  name:"Geometric Metallic Luxe Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.85, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_22_14 AM.png", desc:"Modern architectural cake with rose gold marble textures and sharp lines.", active:true },
    { id:63,  name:"Tropical Paradise Botanical Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_25_11 AM.png", desc:"Exotic passionfruit and mango cake adorned with handcrafted sugar orchids.", active:true },
    { id:64,  name:"Sweet Mermaid Ocean Wave Cake",     category:"customized-cakes", tag:"Custom Design", basePrice:1450, originalPrice:1950, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_27_30 AM.png", desc:"Iridescent seafoam mermaid tail cake with chocolate pearls and ocean waves.", active:true },
    { id:65,  name:"Pastel Balloon Fiesta Cake",        category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.88, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_30_52 AM.png", desc:"Festive birthday cake topped with edible mini fondant balloon cluster.", active:true },
    { id:66,  name:"Luxury Car & Speedster Cake",       category:"customized-cakes", tag:"Custom Design", basePrice:1599, originalPrice:2199, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_39_14 AM.png", desc:"3D sculpted sports car theme cake for motorsport enthusiasts.", active:true },
    { id:67,  name:"Romantic Cherry Blossom Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_42_25 AM.png", desc:"Japanese sakura branch hand-piped over light white chocolate mousse.", active:true },
    { id:68,  name:"Super Hero Emblem Cake",           category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_46_39 AM.png", desc:"Action-packed 3D superhero emblem cake with chocolate truffle filling.", active:true },
    { id:69,  name:"Golden Monogram Elegance Cake",     category:"customized-cakes", tag:"Custom Design", basePrice:1450, originalPrice:1950, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_50_37 AM.png", desc:"Personalized gold monogram crest cake with white truffle and vanilla bean.", active:true },
    { id:70,  name:"Little Dinosaur Adventure Cake",    category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.88, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_53_51 AM.png", desc:"Playful dino safari cake with chocolate soil and hand-modeled dinosaurs.", active:true },
    { id:71,  name:"Shimmering Diamond Luxe Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1699, originalPrice:2299, offerText:"Customized to order", rating:4.98, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 10_57_52 AM.png", desc:"Diamond faceted geode cake with edible crystal quartz and silver leaf.", active:true },
    { id:72,  name:"Vintage Teaparty & Lace Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_01_13 AM.png", desc:"Delicate sugar lace and teapot topper cake for high-tea celebrations.", active:true },
    { id:73,  name:"Astronaut Space Odyssey Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1450, originalPrice:1950, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_09_29 AM.png", desc:"Out-of-this-world astronaut cake with planet spheres and dark cocoa.", active:true },
    { id:74,  name:"Gourmet Macaron & Berry Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.94, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_13_43 AM.png", desc:"Stacked french macarons and fresh berries over swiss meringue buttercream.", active:true },
    { id:75,  name:"Rose Gold Sequins Cake",            category:"customized-cakes", tag:"Custom Design", basePrice:1550, originalPrice:2050, offerText:"Customized to order", rating:4.96, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_15_25 AM.png", desc:"Hand-applied edible rose gold confetti sequins with red velvet layers.", active:true },
    { id:76,  name:"Cute Panda Bamboo Grove Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.89, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_17_38 AM.png", desc:"Adorable panda bear eating sugar bamboo shoots over cookies and cream.", active:true },
    { id:77,  name:"Choco Drip & Donut Tower Cake",     category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.91, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_20_25 AM.png", desc:"Over-the-top drip cake loaded with glazed mini donuts and chocolate bars.", active:true },
    { id:78,  name:"Blush Peony Engagement Cake",       category:"customized-cakes", tag:"Custom Design", basePrice:1799, originalPrice:2399, offerText:"Customized to order", rating:4.99, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_35_32 AM.png", desc:"Romantic 3-tier engagement cake with oversized sugar peony flowers.", active:true },
    { id:79,  name:"Golden Safari Lion King Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1450, originalPrice:1950, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_41_01 AM.png", desc:"Majestic golden lion king 1st birthday theme cake with jungle leaves.", active:true },
    { id:80,  name:"Coquette Ribbon & Heart Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.93, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_43_50 AM.png", desc:"Trendy coquette heart shaped cake with pink ruffled piping and satin bows.", active:true },
    { id:81,  name:"Crystal Chandelier Luxe Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1899, originalPrice:2499, offerText:"Customized to order", rating:4.99, img:"./ai cakes/ai cakes/ChatGPT Image Aug 7, 2026, 11_46_32 AM.png", desc:"Showstopping crystal chandelier wedding cake with edible glass crystals.", active:true },
    { id:82,  name:"Buttercream Ombre Cascade Cake",     category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.87, img:"./ai cakes/ai cakes/Gemini_Generated_Image_4gw3nx4gw3nx4gw3.png", desc:"Gradient ombre buttercream cake with delicate white sugar hydrangeas.", active:true },
    { id:83,  name:"Velvet Berry Crown Cake",            category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/Gemini_Generated_Image_5k081u5k081u5k08.png", desc:"Rich red velvet sponge crowned with fresh raspberries and gold dusting.", active:true },
    { id:84,  name:"Magical Harry Potter Spell Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/Gemini_Generated_Image_6v1tu86v1tu86v1t.png", desc:"Wizarding world themed cake with golden snitch and magic spellbook.", active:true },
    { id:85,  name:"Cute Bunny Meadow Birthday Cake",    category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.89, img:"./ai cakes/ai cakes/Gemini_Generated_Image_7a079l7a079l7a07.png", desc:"Sweet little bunny rabbit in a floral meadow for 1st birthday celebrations.", active:true },
    { id:86,  name:"Dark Chocolate Truffle Geode Cake",  category:"customized-cakes", tag:"Custom Design", basePrice:1599, originalPrice:2099, offerText:"Customized to order", rating:4.96, img:"./ai cakes/ai cakes/Gemini_Generated_Image_7zzywf7zzywf7zzy.png", desc:"Intense dark Belgian chocolate cake featuring amethyst rock crystal geode.", active:true },
    { id:87,  name:"Golden Anniversary 50th Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1799, originalPrice:2399, offerText:"Customized to order", rating:4.98, img:"./ai cakes/ai cakes/Gemini_Generated_Image_8ihknx8ihknx8ihk.png", desc:"Grand 50th golden jubilee cake with shimmering gold leaf and vanilla bean.", active:true },
    { id:88,  name:"Spiderman City Skyline Cake",        category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/Gemini_Generated_Image_aj9m98aj9m98aj9m.png", desc:"3D Spiderman web-slinging over midnight city skyscraper cake.", active:true },
    { id:89,  name:"Sweet Candy Kingdom Cake",           category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.88, img:"./ai cakes/ai cakes/Gemini_Generated_Image_ap1j7jap1j7jap1j.png", desc:"Whimsical candy land cake with giant lollipops and gumdrop waterfall.", active:true },
    { id:90,  name:"Minimalist Texture Art Cake",        category:"customized-cakes", tag:"Custom Design", basePrice:1250, originalPrice:1699, offerText:"Customized to order", rating:4.86, img:"./ai cakes/ai cakes/Gemini_Generated_Image_arnl2garnl2garnl.png", desc:"Contemporary palette knife textured cake with subtle gold leaf stroke.", active:true },
    { id:91,  name:"Frozen Elsa Ice Castle Cake",        category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/Gemini_Generated_Image_bx7cdlbx7cdlbx7c.png", desc:"Winter wonderland ice castle cake with translucent isomalt sugar crystals.", active:true },
    { id:92,  name:"White Gold Elegance Wedding Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1899, originalPrice:2499, offerText:"Customized to order", rating:4.99, img:"./ai cakes/ai cakes/Gemini_Generated_Image_c1urjlc1urjlc1ur.png", desc:"Pristine 3-tier white wedding cake with delicate sugar lace and gold leaf.", active:true },
    { id:93,  name:"Basketball MVP Sports Cake",        category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.89, img:"./ai cakes/ai cakes/Gemini_Generated_Image_djavi1djavi1djav.png", desc:"3D sculpted basketball theme cake for sports champions.", active:true },
    { id:94,  name:"Vintage Clockwork Steampunk Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1599, originalPrice:2099, offerText:"Customized to order", rating:4.93, img:"./ai cakes/ai cakes/Gemini_Generated_Image_dmqt3bdmqt3bdmqt.png", desc:"Intricate steampunk clockwork cake with metallic bronze cogs and gears.", active:true },
    { id:95,  name:"Pastel Rainbow Cloud Droplets Cake", category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/Gemini_Generated_Image_fxrzdvfxrzdvfxrz.png", desc:"Soft pastel rainbow gradient cake with fluffy marshmallows and sprinkles.", active:true },
    { id:96,  name:"Choco Mocha Hazelnut Luxe Cake",     category:"customized-cakes", tag:"Custom Design", basePrice:1450, originalPrice:1950, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/Gemini_Generated_Image_i5jhhai5jhhai5jh.png", desc:"Rich espresso coffee sponge with roasted hazelnuts and dark ganache.", active:true },
    { id:97,  name:"Cute Kitten Ball of Yarn Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1299, originalPrice:1799, offerText:"Customized to order", rating:4.88, img:"./ai cakes/ai cakes/Gemini_Generated_Image_jc87djjc87djjc87.png", desc:"Playful kitten playing with sugar yarn ball for cat lovers.", active:true },
    { id:98,  name:"Royal Emerald & Gold Marble Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1699, originalPrice:2299, offerText:"Customized to order", rating:4.97, img:"./ai cakes/ai cakes/Gemini_Generated_Image_jqz6p8jqz6p8jqz6.png", desc:"Stunning emerald green marble finish cake with gold veining.", active:true },
    { id:99,  name:"Little Princess Tiara Cake",         category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.91, img:"./ai cakes/ai cakes/Gemini_Generated_Image_k9sjcvk9sjcvk9sj.png", desc:"Pink pearl tiara cake crafted for royal little princesses.", active:true },
    { id:100, name:"Rustic Wildflower Meadow Cake",     category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.89, img:"./ai cakes/ai cakes/Gemini_Generated_Image_l959stl959stl959.png", desc:"Semi-naked rustic cake decorated with fresh wildflowers and honey drizzle.", active:true },
    { id:101, name:"Ferrero Rocher Tower Cake",         category:"customized-cakes", tag:"Custom Design", basePrice:1599, originalPrice:2099, offerText:"Customized to order", rating:4.96, img:"./ai cakes/ai cakes/Gemini_Generated_Image_lkhv35lkhv35lkhv.png", desc:"Pyramid tower of Ferrero Rocher chocolates over hazelnut praline.", active:true },
    { id:102, name:"Cute Elephant Balloon 1st Birthday", category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/Gemini_Generated_Image_m3w5z2m3w5z2m3w5.png", desc:"Baby elephant holding a 3D sugar balloon for 1st birthday celebrations.", active:true },
    { id:103, name:"Dark Velvet Midnight Skull Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1499, originalPrice:1999, offerText:"Customized to order", rating:4.9,  img:"./ai cakes/ai cakes/Gemini_Generated_Image_nmioh2nmioh2nmio.png", desc:"Dramatic gothic midnight velvet cake with sugar roses and metallic accents.", active:true },
    { id:104, name:"Golden Swan Lake Ballet Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1599, originalPrice:2199, offerText:"Customized to order", rating:4.95, img:"./ai cakes/ai cakes/Gemini_Generated_Image_nv3lvpnv3lvpnv3l.png", desc:"Graceful swan topper with feather piped cream and gold sparkles.", active:true },
    { id:105, name:"Sweet Strawberry Shortcake Tower",  category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.91, img:"./ai cakes/ai cakes/Gemini_Generated_Image_ocec7kocec7kocec.png", desc:"Fresh strawberry shortcake stacked high with vanilla cream and compote.", active:true },
    { id:106, name:"Luxury Watch & Gift Box Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1699, originalPrice:2299, offerText:"Customized to order", rating:4.94, img:"./ai cakes/ai cakes/Gemini_Generated_Image_pr7qkepr7qkepr7q.png", desc:"Gentleman's gift box cake sculpted with realistic luxury watch detail.", active:true },
    { id:107, name:"Pastel Rainbow Unicorn Dreams",    category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/Gemini_Generated_Image_sls7clsls7clsls7.png", desc:"Delightful pastel unicorn cake with gold eyelash detailing.", active:true },
    { id:108, name:"Choco Overload Brownie Blast Cake",category:"customized-cakes", tag:"Custom Design", basePrice:1450, originalPrice:1950, offerText:"Customized to order", rating:4.93, img:"./ai cakes/ai cakes/Gemini_Generated_Image_sqzvi6sqzvi6sqzv.png", desc:"Loaded with fudgy brownie cubes, chocolate drip, and chocochips.", active:true },
    { id:109, name:"Cute Teddy Moon & Stars Cake",      category:"customized-cakes", tag:"Custom Design", basePrice:1350, originalPrice:1850, offerText:"Customized to order", rating:4.91, img:"./ai cakes/ai cakes/Gemini_Generated_Image_srmr0vsrmr0vsrmr.png", desc:"Teddy bear sitting on crescent moon surrounded by glowing sugar stars.", active:true },
    { id:110, name:"Vintage Red Velvet Ribbon Cake",    category:"customized-cakes", tag:"Custom Design", basePrice:1399, originalPrice:1899, offerText:"Customized to order", rating:4.92, img:"./ai cakes/ai cakes/Gemini_Generated_Image_vbmc2cvbmc2cvbmc.png", desc:"Vintage heart-shaped red velvet cake with ruffled cream and satin bows.", active:true },
    { id:111, name:"Royal Crown & Pillow Cushion Cake",category:"customized-cakes", tag:"Custom Design", basePrice:1699, originalPrice:2299, offerText:"Customized to order", rating:4.96, img:"./ai cakes/ai cakes/Gemini_Generated_Image_vh5mfdvh5mfdvh5m.png", desc:"Quilted pillow cushion cake topped with 3D royal imperial crown.", active:true },
    { id:112, name:"White Orchid Grace Wedding Cake",   category:"customized-cakes", tag:"Custom Design", basePrice:1799, originalPrice:2399, offerText:"Customized to order", rating:4.98, img:"./ai cakes/ai cakes/Gemini_Generated_Image_w2wedww2wedww2we.png", desc:"Pure white wedding cake cascading with elegant sugar orchids.", active:true },
    { id:113, name:"Golden Marble Geode Masterpiece",   category:"customized-cakes", tag:"Custom Design", basePrice:1899, originalPrice:2499, offerText:"Customized to order", rating:4.99, img:"./ai cakes/ai cakes/Gemini_Generated_Image_wdm15wwdm15wwdm1.png", desc:"Bespoke 3-tier golden marble geode cake with edible crystal quartz.", active:true }
  ],

  heroSlides: [
    { name: 'Choco Scotch Cake', img: './cakes/cakes/caramel chocolate.jfif', rating: '4.8★', orders: '33 Google Reviews' },
    { name: 'Red Scotch Cake', img: './cakes/cakes/Red velvet Cake .jfif', rating: '4.9★', orders: '33 Google Reviews' },
    { name: 'Ferro Scotch Cake', img: './cakes/cakes/Southern Caramel Cake_ 5-Star Recipe You Must Try - My Favorite Recipes.jfif', rating: '4.95★', orders: '33 Google Reviews' },
    { name: 'Rasmalai Scotch Cake', img: "./cakes/cakes/Crissie's Homemade _ Colorado Springs CO.jfif", rating: '4.85★', orders: '33 Google Reviews' },
    { name: 'Black Forest Cake', img: './cakes/cakes/Black forest cake recipe.jfif', rating: '4.8★', orders: '33 Google Reviews' },
    { name: 'Strawberry Delight', img: './cakes/cakes/cakestrawberry.jfif', rating: '4.8★', orders: '33 Google Reviews' },
    { name: 'Ritch Choco KitKat Cake', img: './cakes/cakes/download (5).jfif', rating: '4.95★', orders: '33 Google Reviews' },
    { name: 'Mango Premium Cake', img: './cakes/cakes/Mango Chiffon Cake.jfif', rating: '4.9★', orders: '33 Google Reviews' },
    { name: 'White Forest Cake', img: './cakes/cakes/White Forest Cake.jfif', rating: '4.8★', orders: '33 Google Reviews' },
    { name: 'Pineapple Cake', img: './cakes/cakes/Dole Whip Cake.jfif', rating: '4.7★', orders: '33 Google Reviews' },
    { name: 'Butterscotch Cake', img: './cakes2/cakes2/butterscotch.jfif', rating: '4.7★', orders: '33 Google Reviews' },
    { name: 'Blueberry Cake', img: './cakes2/cakes2/Blueberry Cake.jfif', rating: '4.9★', orders: '33 Google Reviews' },
    { name: 'Rasmalai Fusion', img: './cakes2/cakes2/rasmalai cake.jfif', rating: '4.95★', orders: '33 Google Reviews' },
    { name: 'Red Velvet Premium Cake', img: './cakes2/cakes2/Red Velvet White Chocolate.jfif', rating: '4.95★', orders: '33 Google Reviews' },
    { name: 'Tender Coconut Delight', img: './cakes2/cakes2/Dream cake.jfif', rating: '4.9★', orders: '33 Google Reviews' }
  ],

  marqueeItems: [
    { img: "./cakes/cakes/Red velvet Cake .jfif", label: "Red Velvet" },
    { img: "./cakes/cakes/caramel chocolate.jfif", label: "Nutella Delight" },
    { img: "./cakes/cakes/Dole Whip Cake.jfif", label: "Pineapple" },
    { img: "./cakes/cakes/Black forest cake recipe.jfif", label: "Black Forest" },
    { img: "./cakes/cakes/Mango Chiffon Cake.jfif", label: "Mango" },
    { img: "./cakes/cakes/White Forest Cake.jfif", label: "White Forest" },
    { img: "./cakes/cakes/cakestrawberry.jfif", label: "Strawberry" },
    { img: "./cakes/cakes/Dark Chocolate .jfif", label: "Dark Chocolate" },
    { img: "./cakes/cakes/download (5).jfif", label: "Kitkat Nuts" },
    { img: "./cakes/cakes/download (3).jfif", label: "Choco Truffle" },
    { img: "./cakes/cakes/birthday cake.jfif", label: "Birthday Special" },
    { img: "./cakes2/cakes2/butterscotch.jfif", label: "Butterscotch Dream" },
    { img: "./cakes2/cakes2/Blueberry Cake.jfif", label: "Blueberry Blossom" },
    { img: "./cakes2/cakes2/rasmalai cake.jfif", label: "Rasmalai Special" },
    { img: "./cakes2/cakes2/Red Velvet White Chocolate.jfif", label: "Red Velvet White Choco" },
    { img: "./cakes2/cakes2/Dream cake.jfif", label: "Dream Cake Special" },
    { img: "./cakes2/cakes2/cake3.jfif", label: "Luxury Celebration" }
  ],

  brandStory: {
    img1: "./cakes/cakes/Red velvet Cake .jfif",
    img2: "./cakes/cakes/White Forest Cake.jfif",
    img3: "./cakes/cakes/Black forest cake recipe.jfif",
    img4: "./cakes2/cakes2/cake.jfif",
    quote: '"If we wouldn\'t serve it at our own family function, we won\'t sell it to you."',
    body: 'Cake Lover started in Namakkal with one goal — bake cakes the way they should be. Real butter, fresh cream, and no shortcuts. Every cake is made on the day of your order. No frozen bases, no readymade fillings. Just honest baking, every single day.'
  },

  reels: [
    { title: "Red Velvet Special ✨", desc: "Freshly layered cream cheese & crimson sponge", views: "14.2k", shares: "382", img: "./cakes/cakes/Red velvet Cake .jfif", link: "https://www.instagram.com/cakes_lover_namakkal_official/" },
    { title: "Caramel Drizzle Magic 🍯", desc: "Real butterscotch crunch & liquid gold caramel", views: "28.9k", shares: "891", img: "./cakes/cakes/caramel chocolate.jfif", link: "https://www.instagram.com/cakes_lover_namakkal_official/" },
    { title: "German Chocolate Fudge 🍫", desc: "Pure dark chocolate shavings & maraschino cherry", views: "19.5k", shares: "420", img: "./cakes/cakes/Dark Chocolate .jfif", link: "https://www.instagram.com/cakes_lover_namakkal_official/" },
    { title: "Mango Chiffon Delight 🥭", desc: "Fresh Alphonso pulp blended with light cream", views: "11.8k", shares: "215", img: "./cakes/cakes/Mango Chiffon Cake.jfif", link: "https://www.instagram.com/cakes_lover_namakkal_official/" }
  ],

  offerBanner: {
    title: "Today's Offer Ends In:",
    hrs: 3,
    mins: 44,
    secs: 9,
    cta: "Order Now",
    link: "https://wa.me/919159158325"
  }
};
